
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingPreferredSkill` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ListingPreferredSkill
 * 
 */
export type ListingPreferredSkillModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingPreferredSkillPayload>

export type AggregateListingPreferredSkill = {
  _count: ListingPreferredSkillCountAggregateOutputType | null
  _min: ListingPreferredSkillMinAggregateOutputType | null
  _max: ListingPreferredSkillMaxAggregateOutputType | null
}

export type ListingPreferredSkillMinAggregateOutputType = {
  listingId: string | null
  skillId: string | null
}

export type ListingPreferredSkillMaxAggregateOutputType = {
  listingId: string | null
  skillId: string | null
}

export type ListingPreferredSkillCountAggregateOutputType = {
  listingId: number
  skillId: number
  _all: number
}


export type ListingPreferredSkillMinAggregateInputType = {
  listingId?: true
  skillId?: true
}

export type ListingPreferredSkillMaxAggregateInputType = {
  listingId?: true
  skillId?: true
}

export type ListingPreferredSkillCountAggregateInputType = {
  listingId?: true
  skillId?: true
  _all?: true
}

export type ListingPreferredSkillAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingPreferredSkill to aggregate.
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingPreferredSkills to fetch.
   */
  orderBy?: Prisma.ListingPreferredSkillOrderByWithRelationInput | Prisma.ListingPreferredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingPreferredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingPreferredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingPreferredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingPreferredSkills
  **/
  _count?: true | ListingPreferredSkillCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingPreferredSkillMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingPreferredSkillMaxAggregateInputType
}

export type GetListingPreferredSkillAggregateType<T extends ListingPreferredSkillAggregateArgs> = {
      [P in keyof T & keyof AggregateListingPreferredSkill]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingPreferredSkill[P]>
    : Prisma.GetScalarType<T[P], AggregateListingPreferredSkill[P]>
}




export type ListingPreferredSkillGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingPreferredSkillWhereInput
  orderBy?: Prisma.ListingPreferredSkillOrderByWithAggregationInput | Prisma.ListingPreferredSkillOrderByWithAggregationInput[]
  by: Prisma.ListingPreferredSkillScalarFieldEnum[] | Prisma.ListingPreferredSkillScalarFieldEnum
  having?: Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingPreferredSkillCountAggregateInputType | true
  _min?: ListingPreferredSkillMinAggregateInputType
  _max?: ListingPreferredSkillMaxAggregateInputType
}

export type ListingPreferredSkillGroupByOutputType = {
  listingId: string
  skillId: string
  _count: ListingPreferredSkillCountAggregateOutputType | null
  _min: ListingPreferredSkillMinAggregateOutputType | null
  _max: ListingPreferredSkillMaxAggregateOutputType | null
}

export type GetListingPreferredSkillGroupByPayload<T extends ListingPreferredSkillGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingPreferredSkillGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingPreferredSkillGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingPreferredSkillGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingPreferredSkillGroupByOutputType[P]>
      }
    >
  >



export type ListingPreferredSkillWhereInput = {
  AND?: Prisma.ListingPreferredSkillWhereInput | Prisma.ListingPreferredSkillWhereInput[]
  OR?: Prisma.ListingPreferredSkillWhereInput[]
  NOT?: Prisma.ListingPreferredSkillWhereInput | Prisma.ListingPreferredSkillWhereInput[]
  listingId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
  listing?: Prisma.XOR<Prisma.ListingScalarRelationFilter, Prisma.ListingWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type ListingPreferredSkillOrderByWithRelationInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  listing?: Prisma.ListingOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
}

export type ListingPreferredSkillWhereUniqueInput = Prisma.AtLeast<{
  listingId_skillId?: Prisma.ListingPreferredSkillListingIdSkillIdCompoundUniqueInput
  AND?: Prisma.ListingPreferredSkillWhereInput | Prisma.ListingPreferredSkillWhereInput[]
  OR?: Prisma.ListingPreferredSkillWhereInput[]
  NOT?: Prisma.ListingPreferredSkillWhereInput | Prisma.ListingPreferredSkillWhereInput[]
  listingId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
  listing?: Prisma.XOR<Prisma.ListingScalarRelationFilter, Prisma.ListingWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "listingId_skillId">

export type ListingPreferredSkillOrderByWithAggregationInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  _count?: Prisma.ListingPreferredSkillCountOrderByAggregateInput
  _max?: Prisma.ListingPreferredSkillMaxOrderByAggregateInput
  _min?: Prisma.ListingPreferredSkillMinOrderByAggregateInput
}

export type ListingPreferredSkillScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput | Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput | Prisma.ListingPreferredSkillScalarWhereWithAggregatesInput[]
  listingId?: Prisma.StringWithAggregatesFilter<"ListingPreferredSkill"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"ListingPreferredSkill"> | string
}

export type ListingPreferredSkillCreateInput = {
  listing: Prisma.ListingCreateNestedOneWithoutPreferredSkillsInput
  skill: Prisma.SkillCreateNestedOneWithoutPreferredListingsInput
}

export type ListingPreferredSkillUncheckedCreateInput = {
  listingId: string
  skillId: string
}

export type ListingPreferredSkillUpdateInput = {
  listing?: Prisma.ListingUpdateOneRequiredWithoutPreferredSkillsNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutPreferredListingsNestedInput
}

export type ListingPreferredSkillUncheckedUpdateInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingPreferredSkillCreateManyInput = {
  listingId: string
  skillId: string
}

export type ListingPreferredSkillUpdateManyMutationInput = {

}

export type ListingPreferredSkillUncheckedUpdateManyInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingPreferredSkillListRelationFilter = {
  every?: Prisma.ListingPreferredSkillWhereInput
  some?: Prisma.ListingPreferredSkillWhereInput
  none?: Prisma.ListingPreferredSkillWhereInput
}

export type ListingPreferredSkillOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ListingPreferredSkillListingIdSkillIdCompoundUniqueInput = {
  listingId: string
  skillId: string
}

export type ListingPreferredSkillCountOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingPreferredSkillMaxOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingPreferredSkillMinOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingPreferredSkillCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingPreferredSkillCreateWithoutSkillInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManySkillInputEnvelope
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
}

export type ListingPreferredSkillUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingPreferredSkillCreateWithoutSkillInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManySkillInputEnvelope
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
}

export type ListingPreferredSkillUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingPreferredSkillCreateWithoutSkillInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutSkillInput | Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManySkillInputEnvelope
  set?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  delete?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  update?: Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutSkillInput | Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutSkillInput | Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
}

export type ListingPreferredSkillUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingPreferredSkillCreateWithoutSkillInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutSkillInput | Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManySkillInputEnvelope
  set?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  delete?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  update?: Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutSkillInput | Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutSkillInput | Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
}

export type ListingPreferredSkillCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingPreferredSkillCreateWithoutListingInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManyListingInputEnvelope
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
}

export type ListingPreferredSkillUncheckedCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingPreferredSkillCreateWithoutListingInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManyListingInputEnvelope
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
}

export type ListingPreferredSkillUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingPreferredSkillCreateWithoutListingInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutListingInput | Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManyListingInputEnvelope
  set?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  delete?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  update?: Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutListingInput | Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutListingInput | Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
}

export type ListingPreferredSkillUncheckedUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingPreferredSkillCreateWithoutListingInput[] | Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput | Prisma.ListingPreferredSkillCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutListingInput | Prisma.ListingPreferredSkillUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.ListingPreferredSkillCreateManyListingInputEnvelope
  set?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  delete?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  connect?: Prisma.ListingPreferredSkillWhereUniqueInput | Prisma.ListingPreferredSkillWhereUniqueInput[]
  update?: Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutListingInput | Prisma.ListingPreferredSkillUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutListingInput | Prisma.ListingPreferredSkillUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
}

export type ListingPreferredSkillCreateWithoutSkillInput = {
  listing: Prisma.ListingCreateNestedOneWithoutPreferredSkillsInput
}

export type ListingPreferredSkillUncheckedCreateWithoutSkillInput = {
  listingId: string
}

export type ListingPreferredSkillCreateOrConnectWithoutSkillInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput>
}

export type ListingPreferredSkillCreateManySkillInputEnvelope = {
  data: Prisma.ListingPreferredSkillCreateManySkillInput | Prisma.ListingPreferredSkillCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type ListingPreferredSkillUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingPreferredSkillUpdateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutSkillInput>
}

export type ListingPreferredSkillUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateWithoutSkillInput, Prisma.ListingPreferredSkillUncheckedUpdateWithoutSkillInput>
}

export type ListingPreferredSkillUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.ListingPreferredSkillScalarWhereInput
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateManyMutationInput, Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutSkillInput>
}

export type ListingPreferredSkillScalarWhereInput = {
  AND?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
  OR?: Prisma.ListingPreferredSkillScalarWhereInput[]
  NOT?: Prisma.ListingPreferredSkillScalarWhereInput | Prisma.ListingPreferredSkillScalarWhereInput[]
  listingId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingPreferredSkill"> | string
}

export type ListingPreferredSkillCreateWithoutListingInput = {
  skill: Prisma.SkillCreateNestedOneWithoutPreferredListingsInput
}

export type ListingPreferredSkillUncheckedCreateWithoutListingInput = {
  skillId: string
}

export type ListingPreferredSkillCreateOrConnectWithoutListingInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput>
}

export type ListingPreferredSkillCreateManyListingInputEnvelope = {
  data: Prisma.ListingPreferredSkillCreateManyListingInput | Prisma.ListingPreferredSkillCreateManyListingInput[]
  skipDuplicates?: boolean
}

export type ListingPreferredSkillUpsertWithWhereUniqueWithoutListingInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingPreferredSkillUpdateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedUpdateWithoutListingInput>
  create: Prisma.XOR<Prisma.ListingPreferredSkillCreateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedCreateWithoutListingInput>
}

export type ListingPreferredSkillUpdateWithWhereUniqueWithoutListingInput = {
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateWithoutListingInput, Prisma.ListingPreferredSkillUncheckedUpdateWithoutListingInput>
}

export type ListingPreferredSkillUpdateManyWithWhereWithoutListingInput = {
  where: Prisma.ListingPreferredSkillScalarWhereInput
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateManyMutationInput, Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutListingInput>
}

export type ListingPreferredSkillCreateManySkillInput = {
  listingId: string
}

export type ListingPreferredSkillUpdateWithoutSkillInput = {
  listing?: Prisma.ListingUpdateOneRequiredWithoutPreferredSkillsNestedInput
}

export type ListingPreferredSkillUncheckedUpdateWithoutSkillInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingPreferredSkillUncheckedUpdateManyWithoutSkillInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingPreferredSkillCreateManyListingInput = {
  skillId: string
}

export type ListingPreferredSkillUpdateWithoutListingInput = {
  skill?: Prisma.SkillUpdateOneRequiredWithoutPreferredListingsNestedInput
}

export type ListingPreferredSkillUncheckedUpdateWithoutListingInput = {
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingPreferredSkillUncheckedUpdateManyWithoutListingInput = {
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ListingPreferredSkillSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingPreferredSkill"]>

export type ListingPreferredSkillSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingPreferredSkill"]>

export type ListingPreferredSkillSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingPreferredSkill"]>

export type ListingPreferredSkillSelectScalar = {
  listingId?: boolean
  skillId?: boolean
}

export type ListingPreferredSkillOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"listingId" | "skillId", ExtArgs["result"]["listingPreferredSkill"]>
export type ListingPreferredSkillInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type ListingPreferredSkillIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type ListingPreferredSkillIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $ListingPreferredSkillPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingPreferredSkill"
  objects: {
    listing: Prisma.$ListingPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    listingId: string
    skillId: string
  }, ExtArgs["result"]["listingPreferredSkill"]>
  composites: {}
}

export type ListingPreferredSkillGetPayload<S extends boolean | null | undefined | ListingPreferredSkillDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload, S>

export type ListingPreferredSkillCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingPreferredSkillFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingPreferredSkillCountAggregateInputType | true
  }

export interface ListingPreferredSkillDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingPreferredSkill'], meta: { name: 'ListingPreferredSkill' } }
  /**
   * Find zero or one ListingPreferredSkill that matches the filter.
   * @param {ListingPreferredSkillFindUniqueArgs} args - Arguments to find a ListingPreferredSkill
   * @example
   * // Get one ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingPreferredSkillFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingPreferredSkill that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingPreferredSkillFindUniqueOrThrowArgs} args - Arguments to find a ListingPreferredSkill
   * @example
   * // Get one ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingPreferredSkillFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingPreferredSkill that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillFindFirstArgs} args - Arguments to find a ListingPreferredSkill
   * @example
   * // Get one ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingPreferredSkillFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingPreferredSkill that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillFindFirstOrThrowArgs} args - Arguments to find a ListingPreferredSkill
   * @example
   * // Get one ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingPreferredSkillFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingPreferredSkills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingPreferredSkills
   * const listingPreferredSkills = await prisma.listingPreferredSkill.findMany()
   * 
   * // Get first 10 ListingPreferredSkills
   * const listingPreferredSkills = await prisma.listingPreferredSkill.findMany({ take: 10 })
   * 
   * // Only select the `listingId`
   * const listingPreferredSkillWithListingIdOnly = await prisma.listingPreferredSkill.findMany({ select: { listingId: true } })
   * 
   */
  findMany<T extends ListingPreferredSkillFindManyArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingPreferredSkill.
   * @param {ListingPreferredSkillCreateArgs} args - Arguments to create a ListingPreferredSkill.
   * @example
   * // Create one ListingPreferredSkill
   * const ListingPreferredSkill = await prisma.listingPreferredSkill.create({
   *   data: {
   *     // ... data to create a ListingPreferredSkill
   *   }
   * })
   * 
   */
  create<T extends ListingPreferredSkillCreateArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillCreateArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingPreferredSkills.
   * @param {ListingPreferredSkillCreateManyArgs} args - Arguments to create many ListingPreferredSkills.
   * @example
   * // Create many ListingPreferredSkills
   * const listingPreferredSkill = await prisma.listingPreferredSkill.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingPreferredSkillCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingPreferredSkills and returns the data saved in the database.
   * @param {ListingPreferredSkillCreateManyAndReturnArgs} args - Arguments to create many ListingPreferredSkills.
   * @example
   * // Create many ListingPreferredSkills
   * const listingPreferredSkill = await prisma.listingPreferredSkill.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingPreferredSkills and only return the `listingId`
   * const listingPreferredSkillWithListingIdOnly = await prisma.listingPreferredSkill.createManyAndReturn({
   *   select: { listingId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingPreferredSkillCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingPreferredSkill.
   * @param {ListingPreferredSkillDeleteArgs} args - Arguments to delete one ListingPreferredSkill.
   * @example
   * // Delete one ListingPreferredSkill
   * const ListingPreferredSkill = await prisma.listingPreferredSkill.delete({
   *   where: {
   *     // ... filter to delete one ListingPreferredSkill
   *   }
   * })
   * 
   */
  delete<T extends ListingPreferredSkillDeleteArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingPreferredSkill.
   * @param {ListingPreferredSkillUpdateArgs} args - Arguments to update one ListingPreferredSkill.
   * @example
   * // Update one ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingPreferredSkillUpdateArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingPreferredSkills.
   * @param {ListingPreferredSkillDeleteManyArgs} args - Arguments to filter ListingPreferredSkills to delete.
   * @example
   * // Delete a few ListingPreferredSkills
   * const { count } = await prisma.listingPreferredSkill.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingPreferredSkillDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingPreferredSkillDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingPreferredSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingPreferredSkills
   * const listingPreferredSkill = await prisma.listingPreferredSkill.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingPreferredSkillUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingPreferredSkills and returns the data updated in the database.
   * @param {ListingPreferredSkillUpdateManyAndReturnArgs} args - Arguments to update many ListingPreferredSkills.
   * @example
   * // Update many ListingPreferredSkills
   * const listingPreferredSkill = await prisma.listingPreferredSkill.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingPreferredSkills and only return the `listingId`
   * const listingPreferredSkillWithListingIdOnly = await prisma.listingPreferredSkill.updateManyAndReturn({
   *   select: { listingId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingPreferredSkillUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingPreferredSkill.
   * @param {ListingPreferredSkillUpsertArgs} args - Arguments to update or create a ListingPreferredSkill.
   * @example
   * // Update or create a ListingPreferredSkill
   * const listingPreferredSkill = await prisma.listingPreferredSkill.upsert({
   *   create: {
   *     // ... data to create a ListingPreferredSkill
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingPreferredSkill we want to update
   *   }
   * })
   */
  upsert<T extends ListingPreferredSkillUpsertArgs>(args: Prisma.SelectSubset<T, ListingPreferredSkillUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingPreferredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingPreferredSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillCountArgs} args - Arguments to filter ListingPreferredSkills to count.
   * @example
   * // Count the number of ListingPreferredSkills
   * const count = await prisma.listingPreferredSkill.count({
   *   where: {
   *     // ... the filter for the ListingPreferredSkills we want to count
   *   }
   * })
  **/
  count<T extends ListingPreferredSkillCountArgs>(
    args?: Prisma.Subset<T, ListingPreferredSkillCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingPreferredSkillCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingPreferredSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingPreferredSkillAggregateArgs>(args: Prisma.Subset<T, ListingPreferredSkillAggregateArgs>): Prisma.PrismaPromise<GetListingPreferredSkillAggregateType<T>>

  /**
   * Group by ListingPreferredSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingPreferredSkillGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingPreferredSkillGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingPreferredSkillGroupByArgs['orderBy'] }
      : { orderBy?: ListingPreferredSkillGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingPreferredSkillGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingPreferredSkillGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingPreferredSkill model
 */
readonly fields: ListingPreferredSkillFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingPreferredSkill.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingPreferredSkillClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  listing<T extends Prisma.ListingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingDefaultArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingPreferredSkill model
 */
export interface ListingPreferredSkillFieldRefs {
  readonly listingId: Prisma.FieldRef<"ListingPreferredSkill", 'String'>
  readonly skillId: Prisma.FieldRef<"ListingPreferredSkill", 'String'>
}
    

// Custom InputTypes
/**
 * ListingPreferredSkill findUnique
 */
export type ListingPreferredSkillFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingPreferredSkill to fetch.
   */
  where: Prisma.ListingPreferredSkillWhereUniqueInput
}

/**
 * ListingPreferredSkill findUniqueOrThrow
 */
export type ListingPreferredSkillFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingPreferredSkill to fetch.
   */
  where: Prisma.ListingPreferredSkillWhereUniqueInput
}

/**
 * ListingPreferredSkill findFirst
 */
export type ListingPreferredSkillFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingPreferredSkill to fetch.
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingPreferredSkills to fetch.
   */
  orderBy?: Prisma.ListingPreferredSkillOrderByWithRelationInput | Prisma.ListingPreferredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingPreferredSkills.
   */
  cursor?: Prisma.ListingPreferredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingPreferredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingPreferredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingPreferredSkills.
   */
  distinct?: Prisma.ListingPreferredSkillScalarFieldEnum | Prisma.ListingPreferredSkillScalarFieldEnum[]
}

/**
 * ListingPreferredSkill findFirstOrThrow
 */
export type ListingPreferredSkillFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingPreferredSkill to fetch.
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingPreferredSkills to fetch.
   */
  orderBy?: Prisma.ListingPreferredSkillOrderByWithRelationInput | Prisma.ListingPreferredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingPreferredSkills.
   */
  cursor?: Prisma.ListingPreferredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingPreferredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingPreferredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingPreferredSkills.
   */
  distinct?: Prisma.ListingPreferredSkillScalarFieldEnum | Prisma.ListingPreferredSkillScalarFieldEnum[]
}

/**
 * ListingPreferredSkill findMany
 */
export type ListingPreferredSkillFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingPreferredSkills to fetch.
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingPreferredSkills to fetch.
   */
  orderBy?: Prisma.ListingPreferredSkillOrderByWithRelationInput | Prisma.ListingPreferredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingPreferredSkills.
   */
  cursor?: Prisma.ListingPreferredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingPreferredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingPreferredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingPreferredSkills.
   */
  distinct?: Prisma.ListingPreferredSkillScalarFieldEnum | Prisma.ListingPreferredSkillScalarFieldEnum[]
}

/**
 * ListingPreferredSkill create
 */
export type ListingPreferredSkillCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * The data needed to create a ListingPreferredSkill.
   */
  data: Prisma.XOR<Prisma.ListingPreferredSkillCreateInput, Prisma.ListingPreferredSkillUncheckedCreateInput>
}

/**
 * ListingPreferredSkill createMany
 */
export type ListingPreferredSkillCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingPreferredSkills.
   */
  data: Prisma.ListingPreferredSkillCreateManyInput | Prisma.ListingPreferredSkillCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingPreferredSkill createManyAndReturn
 */
export type ListingPreferredSkillCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * The data used to create many ListingPreferredSkills.
   */
  data: Prisma.ListingPreferredSkillCreateManyInput | Prisma.ListingPreferredSkillCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ListingPreferredSkill update
 */
export type ListingPreferredSkillUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * The data needed to update a ListingPreferredSkill.
   */
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateInput, Prisma.ListingPreferredSkillUncheckedUpdateInput>
  /**
   * Choose, which ListingPreferredSkill to update.
   */
  where: Prisma.ListingPreferredSkillWhereUniqueInput
}

/**
 * ListingPreferredSkill updateMany
 */
export type ListingPreferredSkillUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingPreferredSkills.
   */
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateManyMutationInput, Prisma.ListingPreferredSkillUncheckedUpdateManyInput>
  /**
   * Filter which ListingPreferredSkills to update
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * Limit how many ListingPreferredSkills to update.
   */
  limit?: number
}

/**
 * ListingPreferredSkill updateManyAndReturn
 */
export type ListingPreferredSkillUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * The data used to update ListingPreferredSkills.
   */
  data: Prisma.XOR<Prisma.ListingPreferredSkillUpdateManyMutationInput, Prisma.ListingPreferredSkillUncheckedUpdateManyInput>
  /**
   * Filter which ListingPreferredSkills to update
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * Limit how many ListingPreferredSkills to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ListingPreferredSkill upsert
 */
export type ListingPreferredSkillUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * The filter to search for the ListingPreferredSkill to update in case it exists.
   */
  where: Prisma.ListingPreferredSkillWhereUniqueInput
  /**
   * In case the ListingPreferredSkill found by the `where` argument doesn't exist, create a new ListingPreferredSkill with this data.
   */
  create: Prisma.XOR<Prisma.ListingPreferredSkillCreateInput, Prisma.ListingPreferredSkillUncheckedCreateInput>
  /**
   * In case the ListingPreferredSkill was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingPreferredSkillUpdateInput, Prisma.ListingPreferredSkillUncheckedUpdateInput>
}

/**
 * ListingPreferredSkill delete
 */
export type ListingPreferredSkillDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  /**
   * Filter which ListingPreferredSkill to delete.
   */
  where: Prisma.ListingPreferredSkillWhereUniqueInput
}

/**
 * ListingPreferredSkill deleteMany
 */
export type ListingPreferredSkillDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingPreferredSkills to delete
   */
  where?: Prisma.ListingPreferredSkillWhereInput
  /**
   * Limit how many ListingPreferredSkills to delete.
   */
  limit?: number
}

/**
 * ListingPreferredSkill without action
 */
export type ListingPreferredSkillDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
}
