
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingRequiredSkill` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ListingRequiredSkill
 * 
 */
export type ListingRequiredSkillModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingRequiredSkillPayload>

export type AggregateListingRequiredSkill = {
  _count: ListingRequiredSkillCountAggregateOutputType | null
  _min: ListingRequiredSkillMinAggregateOutputType | null
  _max: ListingRequiredSkillMaxAggregateOutputType | null
}

export type ListingRequiredSkillMinAggregateOutputType = {
  listingId: string | null
  skillId: string | null
}

export type ListingRequiredSkillMaxAggregateOutputType = {
  listingId: string | null
  skillId: string | null
}

export type ListingRequiredSkillCountAggregateOutputType = {
  listingId: number
  skillId: number
  _all: number
}


export type ListingRequiredSkillMinAggregateInputType = {
  listingId?: true
  skillId?: true
}

export type ListingRequiredSkillMaxAggregateInputType = {
  listingId?: true
  skillId?: true
}

export type ListingRequiredSkillCountAggregateInputType = {
  listingId?: true
  skillId?: true
  _all?: true
}

export type ListingRequiredSkillAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingRequiredSkill to aggregate.
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingRequiredSkills to fetch.
   */
  orderBy?: Prisma.ListingRequiredSkillOrderByWithRelationInput | Prisma.ListingRequiredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingRequiredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingRequiredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingRequiredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingRequiredSkills
  **/
  _count?: true | ListingRequiredSkillCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingRequiredSkillMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingRequiredSkillMaxAggregateInputType
}

export type GetListingRequiredSkillAggregateType<T extends ListingRequiredSkillAggregateArgs> = {
      [P in keyof T & keyof AggregateListingRequiredSkill]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingRequiredSkill[P]>
    : Prisma.GetScalarType<T[P], AggregateListingRequiredSkill[P]>
}




export type ListingRequiredSkillGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingRequiredSkillWhereInput
  orderBy?: Prisma.ListingRequiredSkillOrderByWithAggregationInput | Prisma.ListingRequiredSkillOrderByWithAggregationInput[]
  by: Prisma.ListingRequiredSkillScalarFieldEnum[] | Prisma.ListingRequiredSkillScalarFieldEnum
  having?: Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingRequiredSkillCountAggregateInputType | true
  _min?: ListingRequiredSkillMinAggregateInputType
  _max?: ListingRequiredSkillMaxAggregateInputType
}

export type ListingRequiredSkillGroupByOutputType = {
  listingId: string
  skillId: string
  _count: ListingRequiredSkillCountAggregateOutputType | null
  _min: ListingRequiredSkillMinAggregateOutputType | null
  _max: ListingRequiredSkillMaxAggregateOutputType | null
}

export type GetListingRequiredSkillGroupByPayload<T extends ListingRequiredSkillGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingRequiredSkillGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingRequiredSkillGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingRequiredSkillGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingRequiredSkillGroupByOutputType[P]>
      }
    >
  >



export type ListingRequiredSkillWhereInput = {
  AND?: Prisma.ListingRequiredSkillWhereInput | Prisma.ListingRequiredSkillWhereInput[]
  OR?: Prisma.ListingRequiredSkillWhereInput[]
  NOT?: Prisma.ListingRequiredSkillWhereInput | Prisma.ListingRequiredSkillWhereInput[]
  listingId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
  listing?: Prisma.XOR<Prisma.ListingScalarRelationFilter, Prisma.ListingWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type ListingRequiredSkillOrderByWithRelationInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  listing?: Prisma.ListingOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
}

export type ListingRequiredSkillWhereUniqueInput = Prisma.AtLeast<{
  listingId_skillId?: Prisma.ListingRequiredSkillListingIdSkillIdCompoundUniqueInput
  AND?: Prisma.ListingRequiredSkillWhereInput | Prisma.ListingRequiredSkillWhereInput[]
  OR?: Prisma.ListingRequiredSkillWhereInput[]
  NOT?: Prisma.ListingRequiredSkillWhereInput | Prisma.ListingRequiredSkillWhereInput[]
  listingId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
  listing?: Prisma.XOR<Prisma.ListingScalarRelationFilter, Prisma.ListingWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "listingId_skillId">

export type ListingRequiredSkillOrderByWithAggregationInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  _count?: Prisma.ListingRequiredSkillCountOrderByAggregateInput
  _max?: Prisma.ListingRequiredSkillMaxOrderByAggregateInput
  _min?: Prisma.ListingRequiredSkillMinOrderByAggregateInput
}

export type ListingRequiredSkillScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput | Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput | Prisma.ListingRequiredSkillScalarWhereWithAggregatesInput[]
  listingId?: Prisma.StringWithAggregatesFilter<"ListingRequiredSkill"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"ListingRequiredSkill"> | string
}

export type ListingRequiredSkillCreateInput = {
  listing: Prisma.ListingCreateNestedOneWithoutRequiredSkillsInput
  skill: Prisma.SkillCreateNestedOneWithoutRequiredListingsInput
}

export type ListingRequiredSkillUncheckedCreateInput = {
  listingId: string
  skillId: string
}

export type ListingRequiredSkillUpdateInput = {
  listing?: Prisma.ListingUpdateOneRequiredWithoutRequiredSkillsNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutRequiredListingsNestedInput
}

export type ListingRequiredSkillUncheckedUpdateInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingRequiredSkillCreateManyInput = {
  listingId: string
  skillId: string
}

export type ListingRequiredSkillUpdateManyMutationInput = {

}

export type ListingRequiredSkillUncheckedUpdateManyInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingRequiredSkillListRelationFilter = {
  every?: Prisma.ListingRequiredSkillWhereInput
  some?: Prisma.ListingRequiredSkillWhereInput
  none?: Prisma.ListingRequiredSkillWhereInput
}

export type ListingRequiredSkillOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ListingRequiredSkillListingIdSkillIdCompoundUniqueInput = {
  listingId: string
  skillId: string
}

export type ListingRequiredSkillCountOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingRequiredSkillMaxOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingRequiredSkillMinOrderByAggregateInput = {
  listingId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type ListingRequiredSkillCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingRequiredSkillCreateWithoutSkillInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManySkillInputEnvelope
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
}

export type ListingRequiredSkillUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingRequiredSkillCreateWithoutSkillInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManySkillInputEnvelope
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
}

export type ListingRequiredSkillUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingRequiredSkillCreateWithoutSkillInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutSkillInput | Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManySkillInputEnvelope
  set?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  delete?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  update?: Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutSkillInput | Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutSkillInput | Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
}

export type ListingRequiredSkillUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput> | Prisma.ListingRequiredSkillCreateWithoutSkillInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutSkillInput | Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManySkillInputEnvelope
  set?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  delete?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  update?: Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutSkillInput | Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutSkillInput | Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
}

export type ListingRequiredSkillCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingRequiredSkillCreateWithoutListingInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManyListingInputEnvelope
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
}

export type ListingRequiredSkillUncheckedCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingRequiredSkillCreateWithoutListingInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManyListingInputEnvelope
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
}

export type ListingRequiredSkillUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingRequiredSkillCreateWithoutListingInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutListingInput | Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManyListingInputEnvelope
  set?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  delete?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  update?: Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutListingInput | Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutListingInput | Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
}

export type ListingRequiredSkillUncheckedUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput> | Prisma.ListingRequiredSkillCreateWithoutListingInput[] | Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput | Prisma.ListingRequiredSkillCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutListingInput | Prisma.ListingRequiredSkillUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.ListingRequiredSkillCreateManyListingInputEnvelope
  set?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  disconnect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  delete?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  connect?: Prisma.ListingRequiredSkillWhereUniqueInput | Prisma.ListingRequiredSkillWhereUniqueInput[]
  update?: Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutListingInput | Prisma.ListingRequiredSkillUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutListingInput | Prisma.ListingRequiredSkillUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
}

export type ListingRequiredSkillCreateWithoutSkillInput = {
  listing: Prisma.ListingCreateNestedOneWithoutRequiredSkillsInput
}

export type ListingRequiredSkillUncheckedCreateWithoutSkillInput = {
  listingId: string
}

export type ListingRequiredSkillCreateOrConnectWithoutSkillInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput>
}

export type ListingRequiredSkillCreateManySkillInputEnvelope = {
  data: Prisma.ListingRequiredSkillCreateManySkillInput | Prisma.ListingRequiredSkillCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type ListingRequiredSkillUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingRequiredSkillUpdateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutSkillInput>
}

export type ListingRequiredSkillUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateWithoutSkillInput, Prisma.ListingRequiredSkillUncheckedUpdateWithoutSkillInput>
}

export type ListingRequiredSkillUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.ListingRequiredSkillScalarWhereInput
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateManyMutationInput, Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutSkillInput>
}

export type ListingRequiredSkillScalarWhereInput = {
  AND?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
  OR?: Prisma.ListingRequiredSkillScalarWhereInput[]
  NOT?: Prisma.ListingRequiredSkillScalarWhereInput | Prisma.ListingRequiredSkillScalarWhereInput[]
  listingId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
  skillId?: Prisma.StringFilter<"ListingRequiredSkill"> | string
}

export type ListingRequiredSkillCreateWithoutListingInput = {
  skill: Prisma.SkillCreateNestedOneWithoutRequiredListingsInput
}

export type ListingRequiredSkillUncheckedCreateWithoutListingInput = {
  skillId: string
}

export type ListingRequiredSkillCreateOrConnectWithoutListingInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput>
}

export type ListingRequiredSkillCreateManyListingInputEnvelope = {
  data: Prisma.ListingRequiredSkillCreateManyListingInput | Prisma.ListingRequiredSkillCreateManyListingInput[]
  skipDuplicates?: boolean
}

export type ListingRequiredSkillUpsertWithWhereUniqueWithoutListingInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingRequiredSkillUpdateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedUpdateWithoutListingInput>
  create: Prisma.XOR<Prisma.ListingRequiredSkillCreateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedCreateWithoutListingInput>
}

export type ListingRequiredSkillUpdateWithWhereUniqueWithoutListingInput = {
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateWithoutListingInput, Prisma.ListingRequiredSkillUncheckedUpdateWithoutListingInput>
}

export type ListingRequiredSkillUpdateManyWithWhereWithoutListingInput = {
  where: Prisma.ListingRequiredSkillScalarWhereInput
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateManyMutationInput, Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutListingInput>
}

export type ListingRequiredSkillCreateManySkillInput = {
  listingId: string
}

export type ListingRequiredSkillUpdateWithoutSkillInput = {
  listing?: Prisma.ListingUpdateOneRequiredWithoutRequiredSkillsNestedInput
}

export type ListingRequiredSkillUncheckedUpdateWithoutSkillInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingRequiredSkillUncheckedUpdateManyWithoutSkillInput = {
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingRequiredSkillCreateManyListingInput = {
  skillId: string
}

export type ListingRequiredSkillUpdateWithoutListingInput = {
  skill?: Prisma.SkillUpdateOneRequiredWithoutRequiredListingsNestedInput
}

export type ListingRequiredSkillUncheckedUpdateWithoutListingInput = {
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ListingRequiredSkillUncheckedUpdateManyWithoutListingInput = {
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ListingRequiredSkillSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingRequiredSkill"]>

export type ListingRequiredSkillSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingRequiredSkill"]>

export type ListingRequiredSkillSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  listingId?: boolean
  skillId?: boolean
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listingRequiredSkill"]>

export type ListingRequiredSkillSelectScalar = {
  listingId?: boolean
  skillId?: boolean
}

export type ListingRequiredSkillOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"listingId" | "skillId", ExtArgs["result"]["listingRequiredSkill"]>
export type ListingRequiredSkillInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type ListingRequiredSkillIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type ListingRequiredSkillIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.ListingDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $ListingRequiredSkillPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingRequiredSkill"
  objects: {
    listing: Prisma.$ListingPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    listingId: string
    skillId: string
  }, ExtArgs["result"]["listingRequiredSkill"]>
  composites: {}
}

export type ListingRequiredSkillGetPayload<S extends boolean | null | undefined | ListingRequiredSkillDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload, S>

export type ListingRequiredSkillCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingRequiredSkillFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingRequiredSkillCountAggregateInputType | true
  }

export interface ListingRequiredSkillDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingRequiredSkill'], meta: { name: 'ListingRequiredSkill' } }
  /**
   * Find zero or one ListingRequiredSkill that matches the filter.
   * @param {ListingRequiredSkillFindUniqueArgs} args - Arguments to find a ListingRequiredSkill
   * @example
   * // Get one ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingRequiredSkillFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingRequiredSkill that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingRequiredSkillFindUniqueOrThrowArgs} args - Arguments to find a ListingRequiredSkill
   * @example
   * // Get one ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingRequiredSkillFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingRequiredSkill that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillFindFirstArgs} args - Arguments to find a ListingRequiredSkill
   * @example
   * // Get one ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingRequiredSkillFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingRequiredSkill that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillFindFirstOrThrowArgs} args - Arguments to find a ListingRequiredSkill
   * @example
   * // Get one ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingRequiredSkillFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingRequiredSkills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingRequiredSkills
   * const listingRequiredSkills = await prisma.listingRequiredSkill.findMany()
   * 
   * // Get first 10 ListingRequiredSkills
   * const listingRequiredSkills = await prisma.listingRequiredSkill.findMany({ take: 10 })
   * 
   * // Only select the `listingId`
   * const listingRequiredSkillWithListingIdOnly = await prisma.listingRequiredSkill.findMany({ select: { listingId: true } })
   * 
   */
  findMany<T extends ListingRequiredSkillFindManyArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingRequiredSkill.
   * @param {ListingRequiredSkillCreateArgs} args - Arguments to create a ListingRequiredSkill.
   * @example
   * // Create one ListingRequiredSkill
   * const ListingRequiredSkill = await prisma.listingRequiredSkill.create({
   *   data: {
   *     // ... data to create a ListingRequiredSkill
   *   }
   * })
   * 
   */
  create<T extends ListingRequiredSkillCreateArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillCreateArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingRequiredSkills.
   * @param {ListingRequiredSkillCreateManyArgs} args - Arguments to create many ListingRequiredSkills.
   * @example
   * // Create many ListingRequiredSkills
   * const listingRequiredSkill = await prisma.listingRequiredSkill.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingRequiredSkillCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingRequiredSkills and returns the data saved in the database.
   * @param {ListingRequiredSkillCreateManyAndReturnArgs} args - Arguments to create many ListingRequiredSkills.
   * @example
   * // Create many ListingRequiredSkills
   * const listingRequiredSkill = await prisma.listingRequiredSkill.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingRequiredSkills and only return the `listingId`
   * const listingRequiredSkillWithListingIdOnly = await prisma.listingRequiredSkill.createManyAndReturn({
   *   select: { listingId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingRequiredSkillCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingRequiredSkill.
   * @param {ListingRequiredSkillDeleteArgs} args - Arguments to delete one ListingRequiredSkill.
   * @example
   * // Delete one ListingRequiredSkill
   * const ListingRequiredSkill = await prisma.listingRequiredSkill.delete({
   *   where: {
   *     // ... filter to delete one ListingRequiredSkill
   *   }
   * })
   * 
   */
  delete<T extends ListingRequiredSkillDeleteArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingRequiredSkill.
   * @param {ListingRequiredSkillUpdateArgs} args - Arguments to update one ListingRequiredSkill.
   * @example
   * // Update one ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingRequiredSkillUpdateArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingRequiredSkills.
   * @param {ListingRequiredSkillDeleteManyArgs} args - Arguments to filter ListingRequiredSkills to delete.
   * @example
   * // Delete a few ListingRequiredSkills
   * const { count } = await prisma.listingRequiredSkill.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingRequiredSkillDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingRequiredSkillDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingRequiredSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingRequiredSkills
   * const listingRequiredSkill = await prisma.listingRequiredSkill.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingRequiredSkillUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingRequiredSkills and returns the data updated in the database.
   * @param {ListingRequiredSkillUpdateManyAndReturnArgs} args - Arguments to update many ListingRequiredSkills.
   * @example
   * // Update many ListingRequiredSkills
   * const listingRequiredSkill = await prisma.listingRequiredSkill.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingRequiredSkills and only return the `listingId`
   * const listingRequiredSkillWithListingIdOnly = await prisma.listingRequiredSkill.updateManyAndReturn({
   *   select: { listingId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingRequiredSkillUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingRequiredSkill.
   * @param {ListingRequiredSkillUpsertArgs} args - Arguments to update or create a ListingRequiredSkill.
   * @example
   * // Update or create a ListingRequiredSkill
   * const listingRequiredSkill = await prisma.listingRequiredSkill.upsert({
   *   create: {
   *     // ... data to create a ListingRequiredSkill
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingRequiredSkill we want to update
   *   }
   * })
   */
  upsert<T extends ListingRequiredSkillUpsertArgs>(args: Prisma.SelectSubset<T, ListingRequiredSkillUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingRequiredSkillClient<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingRequiredSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillCountArgs} args - Arguments to filter ListingRequiredSkills to count.
   * @example
   * // Count the number of ListingRequiredSkills
   * const count = await prisma.listingRequiredSkill.count({
   *   where: {
   *     // ... the filter for the ListingRequiredSkills we want to count
   *   }
   * })
  **/
  count<T extends ListingRequiredSkillCountArgs>(
    args?: Prisma.Subset<T, ListingRequiredSkillCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingRequiredSkillCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingRequiredSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingRequiredSkillAggregateArgs>(args: Prisma.Subset<T, ListingRequiredSkillAggregateArgs>): Prisma.PrismaPromise<GetListingRequiredSkillAggregateType<T>>

  /**
   * Group by ListingRequiredSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingRequiredSkillGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingRequiredSkillGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingRequiredSkillGroupByArgs['orderBy'] }
      : { orderBy?: ListingRequiredSkillGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingRequiredSkillGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingRequiredSkillGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingRequiredSkill model
 */
readonly fields: ListingRequiredSkillFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingRequiredSkill.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingRequiredSkillClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  listing<T extends Prisma.ListingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListingDefaultArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingRequiredSkill model
 */
export interface ListingRequiredSkillFieldRefs {
  readonly listingId: Prisma.FieldRef<"ListingRequiredSkill", 'String'>
  readonly skillId: Prisma.FieldRef<"ListingRequiredSkill", 'String'>
}
    

// Custom InputTypes
/**
 * ListingRequiredSkill findUnique
 */
export type ListingRequiredSkillFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingRequiredSkill to fetch.
   */
  where: Prisma.ListingRequiredSkillWhereUniqueInput
}

/**
 * ListingRequiredSkill findUniqueOrThrow
 */
export type ListingRequiredSkillFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingRequiredSkill to fetch.
   */
  where: Prisma.ListingRequiredSkillWhereUniqueInput
}

/**
 * ListingRequiredSkill findFirst
 */
export type ListingRequiredSkillFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingRequiredSkill to fetch.
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingRequiredSkills to fetch.
   */
  orderBy?: Prisma.ListingRequiredSkillOrderByWithRelationInput | Prisma.ListingRequiredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingRequiredSkills.
   */
  cursor?: Prisma.ListingRequiredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingRequiredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingRequiredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingRequiredSkills.
   */
  distinct?: Prisma.ListingRequiredSkillScalarFieldEnum | Prisma.ListingRequiredSkillScalarFieldEnum[]
}

/**
 * ListingRequiredSkill findFirstOrThrow
 */
export type ListingRequiredSkillFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingRequiredSkill to fetch.
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingRequiredSkills to fetch.
   */
  orderBy?: Prisma.ListingRequiredSkillOrderByWithRelationInput | Prisma.ListingRequiredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingRequiredSkills.
   */
  cursor?: Prisma.ListingRequiredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingRequiredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingRequiredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingRequiredSkills.
   */
  distinct?: Prisma.ListingRequiredSkillScalarFieldEnum | Prisma.ListingRequiredSkillScalarFieldEnum[]
}

/**
 * ListingRequiredSkill findMany
 */
export type ListingRequiredSkillFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter, which ListingRequiredSkills to fetch.
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingRequiredSkills to fetch.
   */
  orderBy?: Prisma.ListingRequiredSkillOrderByWithRelationInput | Prisma.ListingRequiredSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingRequiredSkills.
   */
  cursor?: Prisma.ListingRequiredSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingRequiredSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingRequiredSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingRequiredSkills.
   */
  distinct?: Prisma.ListingRequiredSkillScalarFieldEnum | Prisma.ListingRequiredSkillScalarFieldEnum[]
}

/**
 * ListingRequiredSkill create
 */
export type ListingRequiredSkillCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * The data needed to create a ListingRequiredSkill.
   */
  data: Prisma.XOR<Prisma.ListingRequiredSkillCreateInput, Prisma.ListingRequiredSkillUncheckedCreateInput>
}

/**
 * ListingRequiredSkill createMany
 */
export type ListingRequiredSkillCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingRequiredSkills.
   */
  data: Prisma.ListingRequiredSkillCreateManyInput | Prisma.ListingRequiredSkillCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingRequiredSkill createManyAndReturn
 */
export type ListingRequiredSkillCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * The data used to create many ListingRequiredSkills.
   */
  data: Prisma.ListingRequiredSkillCreateManyInput | Prisma.ListingRequiredSkillCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ListingRequiredSkill update
 */
export type ListingRequiredSkillUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * The data needed to update a ListingRequiredSkill.
   */
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateInput, Prisma.ListingRequiredSkillUncheckedUpdateInput>
  /**
   * Choose, which ListingRequiredSkill to update.
   */
  where: Prisma.ListingRequiredSkillWhereUniqueInput
}

/**
 * ListingRequiredSkill updateMany
 */
export type ListingRequiredSkillUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingRequiredSkills.
   */
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateManyMutationInput, Prisma.ListingRequiredSkillUncheckedUpdateManyInput>
  /**
   * Filter which ListingRequiredSkills to update
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * Limit how many ListingRequiredSkills to update.
   */
  limit?: number
}

/**
 * ListingRequiredSkill updateManyAndReturn
 */
export type ListingRequiredSkillUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * The data used to update ListingRequiredSkills.
   */
  data: Prisma.XOR<Prisma.ListingRequiredSkillUpdateManyMutationInput, Prisma.ListingRequiredSkillUncheckedUpdateManyInput>
  /**
   * Filter which ListingRequiredSkills to update
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * Limit how many ListingRequiredSkills to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ListingRequiredSkill upsert
 */
export type ListingRequiredSkillUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * The filter to search for the ListingRequiredSkill to update in case it exists.
   */
  where: Prisma.ListingRequiredSkillWhereUniqueInput
  /**
   * In case the ListingRequiredSkill found by the `where` argument doesn't exist, create a new ListingRequiredSkill with this data.
   */
  create: Prisma.XOR<Prisma.ListingRequiredSkillCreateInput, Prisma.ListingRequiredSkillUncheckedCreateInput>
  /**
   * In case the ListingRequiredSkill was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingRequiredSkillUpdateInput, Prisma.ListingRequiredSkillUncheckedUpdateInput>
}

/**
 * ListingRequiredSkill delete
 */
export type ListingRequiredSkillDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  /**
   * Filter which ListingRequiredSkill to delete.
   */
  where: Prisma.ListingRequiredSkillWhereUniqueInput
}

/**
 * ListingRequiredSkill deleteMany
 */
export type ListingRequiredSkillDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingRequiredSkills to delete
   */
  where?: Prisma.ListingRequiredSkillWhereInput
  /**
   * Limit how many ListingRequiredSkills to delete.
   */
  limit?: number
}

/**
 * ListingRequiredSkill without action
 */
export type ListingRequiredSkillDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
}
