
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Listing` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Listing
 * 
 */
export type ListingModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingPayload>

export type AggregateListing = {
  _count: ListingCountAggregateOutputType | null
  _avg: ListingAvgAggregateOutputType | null
  _sum: ListingSumAggregateOutputType | null
  _min: ListingMinAggregateOutputType | null
  _max: ListingMaxAggregateOutputType | null
}

export type ListingAvgAggregateOutputType = {
  stipend: number | null
  maxApplicants: number | null
  currentApplicants: number | null
  targetGradYear: number | null
}

export type ListingSumAggregateOutputType = {
  stipend: number | null
  maxApplicants: number | null
  currentApplicants: number | null
  targetGradYear: number | null
}

export type ListingMinAggregateOutputType = {
  id: string | null
  companyId: string | null
  title: string | null
  description: string | null
  stipend: number | null
  location: $Enums.Location | null
  deadline: Date | null
  maxApplicants: number | null
  currentApplicants: number | null
  status: $Enums.ListingStatus | null
  autoClosedAt: Date | null
  closedReason: string | null
  createdAt: Date | null
  targetBranch: string | null
  targetGradYear: number | null
}

export type ListingMaxAggregateOutputType = {
  id: string | null
  companyId: string | null
  title: string | null
  description: string | null
  stipend: number | null
  location: $Enums.Location | null
  deadline: Date | null
  maxApplicants: number | null
  currentApplicants: number | null
  status: $Enums.ListingStatus | null
  autoClosedAt: Date | null
  closedReason: string | null
  createdAt: Date | null
  targetBranch: string | null
  targetGradYear: number | null
}

export type ListingCountAggregateOutputType = {
  id: number
  companyId: number
  title: number
  description: number
  stipend: number
  location: number
  deadline: number
  maxApplicants: number
  currentApplicants: number
  status: number
  autoClosedAt: number
  closedReason: number
  createdAt: number
  targetBranch: number
  targetGradYear: number
  _all: number
}


export type ListingAvgAggregateInputType = {
  stipend?: true
  maxApplicants?: true
  currentApplicants?: true
  targetGradYear?: true
}

export type ListingSumAggregateInputType = {
  stipend?: true
  maxApplicants?: true
  currentApplicants?: true
  targetGradYear?: true
}

export type ListingMinAggregateInputType = {
  id?: true
  companyId?: true
  title?: true
  description?: true
  stipend?: true
  location?: true
  deadline?: true
  maxApplicants?: true
  currentApplicants?: true
  status?: true
  autoClosedAt?: true
  closedReason?: true
  createdAt?: true
  targetBranch?: true
  targetGradYear?: true
}

export type ListingMaxAggregateInputType = {
  id?: true
  companyId?: true
  title?: true
  description?: true
  stipend?: true
  location?: true
  deadline?: true
  maxApplicants?: true
  currentApplicants?: true
  status?: true
  autoClosedAt?: true
  closedReason?: true
  createdAt?: true
  targetBranch?: true
  targetGradYear?: true
}

export type ListingCountAggregateInputType = {
  id?: true
  companyId?: true
  title?: true
  description?: true
  stipend?: true
  location?: true
  deadline?: true
  maxApplicants?: true
  currentApplicants?: true
  status?: true
  autoClosedAt?: true
  closedReason?: true
  createdAt?: true
  targetBranch?: true
  targetGradYear?: true
  _all?: true
}

export type ListingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Listing to aggregate.
   */
  where?: Prisma.ListingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Listings to fetch.
   */
  orderBy?: Prisma.ListingOrderByWithRelationInput | Prisma.ListingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Listings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Listings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Listings
  **/
  _count?: true | ListingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ListingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ListingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingMaxAggregateInputType
}

export type GetListingAggregateType<T extends ListingAggregateArgs> = {
      [P in keyof T & keyof AggregateListing]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListing[P]>
    : Prisma.GetScalarType<T[P], AggregateListing[P]>
}




export type ListingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingWhereInput
  orderBy?: Prisma.ListingOrderByWithAggregationInput | Prisma.ListingOrderByWithAggregationInput[]
  by: Prisma.ListingScalarFieldEnum[] | Prisma.ListingScalarFieldEnum
  having?: Prisma.ListingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingCountAggregateInputType | true
  _avg?: ListingAvgAggregateInputType
  _sum?: ListingSumAggregateInputType
  _min?: ListingMinAggregateInputType
  _max?: ListingMaxAggregateInputType
}

export type ListingGroupByOutputType = {
  id: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date
  maxApplicants: number
  currentApplicants: number
  status: $Enums.ListingStatus
  autoClosedAt: Date | null
  closedReason: string | null
  createdAt: Date
  targetBranch: string | null
  targetGradYear: number | null
  _count: ListingCountAggregateOutputType | null
  _avg: ListingAvgAggregateOutputType | null
  _sum: ListingSumAggregateOutputType | null
  _min: ListingMinAggregateOutputType | null
  _max: ListingMaxAggregateOutputType | null
}

export type GetListingGroupByPayload<T extends ListingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingGroupByOutputType[P]>
      }
    >
  >



export type ListingWhereInput = {
  AND?: Prisma.ListingWhereInput | Prisma.ListingWhereInput[]
  OR?: Prisma.ListingWhereInput[]
  NOT?: Prisma.ListingWhereInput | Prisma.ListingWhereInput[]
  id?: Prisma.StringFilter<"Listing"> | string
  companyId?: Prisma.StringFilter<"Listing"> | string
  title?: Prisma.StringFilter<"Listing"> | string
  description?: Prisma.StringFilter<"Listing"> | string
  stipend?: Prisma.FloatFilter<"Listing"> | number
  location?: Prisma.EnumLocationFilter<"Listing"> | $Enums.Location
  deadline?: Prisma.DateTimeFilter<"Listing"> | Date | string
  maxApplicants?: Prisma.IntFilter<"Listing"> | number
  currentApplicants?: Prisma.IntFilter<"Listing"> | number
  status?: Prisma.EnumListingStatusFilter<"Listing"> | $Enums.ListingStatus
  autoClosedAt?: Prisma.DateTimeNullableFilter<"Listing"> | Date | string | null
  closedReason?: Prisma.StringNullableFilter<"Listing"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Listing"> | Date | string
  targetBranch?: Prisma.StringNullableFilter<"Listing"> | string | null
  targetGradYear?: Prisma.IntNullableFilter<"Listing"> | number | null
  company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
  requiredSkills?: Prisma.ListingRequiredSkillListRelationFilter
  preferredSkills?: Prisma.ListingPreferredSkillListRelationFilter
  applications?: Prisma.ApplicationListRelationFilter
}

export type ListingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  stipend?: Prisma.SortOrder
  location?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  status?: Prisma.SortOrder
  autoClosedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  closedReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  targetBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  targetGradYear?: Prisma.SortOrderInput | Prisma.SortOrder
  company?: Prisma.CompanyOrderByWithRelationInput
  requiredSkills?: Prisma.ListingRequiredSkillOrderByRelationAggregateInput
  preferredSkills?: Prisma.ListingPreferredSkillOrderByRelationAggregateInput
  applications?: Prisma.ApplicationOrderByRelationAggregateInput
}

export type ListingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ListingWhereInput | Prisma.ListingWhereInput[]
  OR?: Prisma.ListingWhereInput[]
  NOT?: Prisma.ListingWhereInput | Prisma.ListingWhereInput[]
  companyId?: Prisma.StringFilter<"Listing"> | string
  title?: Prisma.StringFilter<"Listing"> | string
  description?: Prisma.StringFilter<"Listing"> | string
  stipend?: Prisma.FloatFilter<"Listing"> | number
  location?: Prisma.EnumLocationFilter<"Listing"> | $Enums.Location
  deadline?: Prisma.DateTimeFilter<"Listing"> | Date | string
  maxApplicants?: Prisma.IntFilter<"Listing"> | number
  currentApplicants?: Prisma.IntFilter<"Listing"> | number
  status?: Prisma.EnumListingStatusFilter<"Listing"> | $Enums.ListingStatus
  autoClosedAt?: Prisma.DateTimeNullableFilter<"Listing"> | Date | string | null
  closedReason?: Prisma.StringNullableFilter<"Listing"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Listing"> | Date | string
  targetBranch?: Prisma.StringNullableFilter<"Listing"> | string | null
  targetGradYear?: Prisma.IntNullableFilter<"Listing"> | number | null
  company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
  requiredSkills?: Prisma.ListingRequiredSkillListRelationFilter
  preferredSkills?: Prisma.ListingPreferredSkillListRelationFilter
  applications?: Prisma.ApplicationListRelationFilter
}, "id">

export type ListingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  stipend?: Prisma.SortOrder
  location?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  status?: Prisma.SortOrder
  autoClosedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  closedReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  targetBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  targetGradYear?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ListingCountOrderByAggregateInput
  _avg?: Prisma.ListingAvgOrderByAggregateInput
  _max?: Prisma.ListingMaxOrderByAggregateInput
  _min?: Prisma.ListingMinOrderByAggregateInput
  _sum?: Prisma.ListingSumOrderByAggregateInput
}

export type ListingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingScalarWhereWithAggregatesInput | Prisma.ListingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingScalarWhereWithAggregatesInput | Prisma.ListingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Listing"> | string
  companyId?: Prisma.StringWithAggregatesFilter<"Listing"> | string
  title?: Prisma.StringWithAggregatesFilter<"Listing"> | string
  description?: Prisma.StringWithAggregatesFilter<"Listing"> | string
  stipend?: Prisma.FloatWithAggregatesFilter<"Listing"> | number
  location?: Prisma.EnumLocationWithAggregatesFilter<"Listing"> | $Enums.Location
  deadline?: Prisma.DateTimeWithAggregatesFilter<"Listing"> | Date | string
  maxApplicants?: Prisma.IntWithAggregatesFilter<"Listing"> | number
  currentApplicants?: Prisma.IntWithAggregatesFilter<"Listing"> | number
  status?: Prisma.EnumListingStatusWithAggregatesFilter<"Listing"> | $Enums.ListingStatus
  autoClosedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Listing"> | Date | string | null
  closedReason?: Prisma.StringNullableWithAggregatesFilter<"Listing"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Listing"> | Date | string
  targetBranch?: Prisma.StringNullableWithAggregatesFilter<"Listing"> | string | null
  targetGradYear?: Prisma.IntNullableWithAggregatesFilter<"Listing"> | number | null
}

export type ListingCreateInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  company: Prisma.CompanyCreateNestedOneWithoutListingsInput
  requiredSkills?: Prisma.ListingRequiredSkillCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutListingInput
}

export type ListingUncheckedCreateInput = {
  id?: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutListingInput
}

export type ListingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  company?: Prisma.CompanyUpdateOneRequiredWithoutListingsNestedInput
  requiredSkills?: Prisma.ListingRequiredSkillUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutListingNestedInput
}

export type ListingCreateManyInput = {
  id?: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
}

export type ListingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ListingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ListingListRelationFilter = {
  every?: Prisma.ListingWhereInput
  some?: Prisma.ListingWhereInput
  none?: Prisma.ListingWhereInput
}

export type ListingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ListingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  stipend?: Prisma.SortOrder
  location?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  status?: Prisma.SortOrder
  autoClosedAt?: Prisma.SortOrder
  closedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  targetBranch?: Prisma.SortOrder
  targetGradYear?: Prisma.SortOrder
}

export type ListingAvgOrderByAggregateInput = {
  stipend?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  targetGradYear?: Prisma.SortOrder
}

export type ListingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  stipend?: Prisma.SortOrder
  location?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  status?: Prisma.SortOrder
  autoClosedAt?: Prisma.SortOrder
  closedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  targetBranch?: Prisma.SortOrder
  targetGradYear?: Prisma.SortOrder
}

export type ListingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  stipend?: Prisma.SortOrder
  location?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  status?: Prisma.SortOrder
  autoClosedAt?: Prisma.SortOrder
  closedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  targetBranch?: Prisma.SortOrder
  targetGradYear?: Prisma.SortOrder
}

export type ListingSumOrderByAggregateInput = {
  stipend?: Prisma.SortOrder
  maxApplicants?: Prisma.SortOrder
  currentApplicants?: Prisma.SortOrder
  targetGradYear?: Prisma.SortOrder
}

export type ListingScalarRelationFilter = {
  is?: Prisma.ListingWhereInput
  isNot?: Prisma.ListingWhereInput
}

export type ListingCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput> | Prisma.ListingCreateWithoutCompanyInput[] | Prisma.ListingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutCompanyInput | Prisma.ListingCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ListingCreateManyCompanyInputEnvelope
  connect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
}

export type ListingUncheckedCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput> | Prisma.ListingCreateWithoutCompanyInput[] | Prisma.ListingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutCompanyInput | Prisma.ListingCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ListingCreateManyCompanyInputEnvelope
  connect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
}

export type ListingUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput> | Prisma.ListingCreateWithoutCompanyInput[] | Prisma.ListingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutCompanyInput | Prisma.ListingCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ListingUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ListingUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ListingCreateManyCompanyInputEnvelope
  set?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  disconnect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  delete?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  connect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  update?: Prisma.ListingUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ListingUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ListingUpdateManyWithWhereWithoutCompanyInput | Prisma.ListingUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ListingScalarWhereInput | Prisma.ListingScalarWhereInput[]
}

export type ListingUncheckedUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput> | Prisma.ListingCreateWithoutCompanyInput[] | Prisma.ListingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutCompanyInput | Prisma.ListingCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ListingUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ListingUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ListingCreateManyCompanyInputEnvelope
  set?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  disconnect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  delete?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  connect?: Prisma.ListingWhereUniqueInput | Prisma.ListingWhereUniqueInput[]
  update?: Prisma.ListingUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ListingUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ListingUpdateManyWithWhereWithoutCompanyInput | Prisma.ListingUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ListingScalarWhereInput | Prisma.ListingScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumLocationFieldUpdateOperationsInput = {
  set?: $Enums.Location
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumListingStatusFieldUpdateOperationsInput = {
  set?: $Enums.ListingStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ListingCreateNestedOneWithoutRequiredSkillsInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutRequiredSkillsInput, Prisma.ListingUncheckedCreateWithoutRequiredSkillsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutRequiredSkillsInput
  connect?: Prisma.ListingWhereUniqueInput
}

export type ListingUpdateOneRequiredWithoutRequiredSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutRequiredSkillsInput, Prisma.ListingUncheckedCreateWithoutRequiredSkillsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutRequiredSkillsInput
  upsert?: Prisma.ListingUpsertWithoutRequiredSkillsInput
  connect?: Prisma.ListingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingUpdateToOneWithWhereWithoutRequiredSkillsInput, Prisma.ListingUpdateWithoutRequiredSkillsInput>, Prisma.ListingUncheckedUpdateWithoutRequiredSkillsInput>
}

export type ListingCreateNestedOneWithoutPreferredSkillsInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutPreferredSkillsInput, Prisma.ListingUncheckedCreateWithoutPreferredSkillsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutPreferredSkillsInput
  connect?: Prisma.ListingWhereUniqueInput
}

export type ListingUpdateOneRequiredWithoutPreferredSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutPreferredSkillsInput, Prisma.ListingUncheckedCreateWithoutPreferredSkillsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutPreferredSkillsInput
  upsert?: Prisma.ListingUpsertWithoutPreferredSkillsInput
  connect?: Prisma.ListingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingUpdateToOneWithWhereWithoutPreferredSkillsInput, Prisma.ListingUpdateWithoutPreferredSkillsInput>, Prisma.ListingUncheckedUpdateWithoutPreferredSkillsInput>
}

export type ListingCreateNestedOneWithoutApplicationsInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutApplicationsInput, Prisma.ListingUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutApplicationsInput
  connect?: Prisma.ListingWhereUniqueInput
}

export type ListingUpdateOneRequiredWithoutApplicationsNestedInput = {
  create?: Prisma.XOR<Prisma.ListingCreateWithoutApplicationsInput, Prisma.ListingUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.ListingCreateOrConnectWithoutApplicationsInput
  upsert?: Prisma.ListingUpsertWithoutApplicationsInput
  connect?: Prisma.ListingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListingUpdateToOneWithWhereWithoutApplicationsInput, Prisma.ListingUpdateWithoutApplicationsInput>, Prisma.ListingUncheckedUpdateWithoutApplicationsInput>
}

export type ListingCreateWithoutCompanyInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  requiredSkills?: Prisma.ListingRequiredSkillCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutListingInput
}

export type ListingUncheckedCreateWithoutCompanyInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutListingInput
}

export type ListingCreateOrConnectWithoutCompanyInput = {
  where: Prisma.ListingWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput>
}

export type ListingCreateManyCompanyInputEnvelope = {
  data: Prisma.ListingCreateManyCompanyInput | Prisma.ListingCreateManyCompanyInput[]
  skipDuplicates?: boolean
}

export type ListingUpsertWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ListingWhereUniqueInput
  update: Prisma.XOR<Prisma.ListingUpdateWithoutCompanyInput, Prisma.ListingUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.ListingCreateWithoutCompanyInput, Prisma.ListingUncheckedCreateWithoutCompanyInput>
}

export type ListingUpdateWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ListingWhereUniqueInput
  data: Prisma.XOR<Prisma.ListingUpdateWithoutCompanyInput, Prisma.ListingUncheckedUpdateWithoutCompanyInput>
}

export type ListingUpdateManyWithWhereWithoutCompanyInput = {
  where: Prisma.ListingScalarWhereInput
  data: Prisma.XOR<Prisma.ListingUpdateManyMutationInput, Prisma.ListingUncheckedUpdateManyWithoutCompanyInput>
}

export type ListingScalarWhereInput = {
  AND?: Prisma.ListingScalarWhereInput | Prisma.ListingScalarWhereInput[]
  OR?: Prisma.ListingScalarWhereInput[]
  NOT?: Prisma.ListingScalarWhereInput | Prisma.ListingScalarWhereInput[]
  id?: Prisma.StringFilter<"Listing"> | string
  companyId?: Prisma.StringFilter<"Listing"> | string
  title?: Prisma.StringFilter<"Listing"> | string
  description?: Prisma.StringFilter<"Listing"> | string
  stipend?: Prisma.FloatFilter<"Listing"> | number
  location?: Prisma.EnumLocationFilter<"Listing"> | $Enums.Location
  deadline?: Prisma.DateTimeFilter<"Listing"> | Date | string
  maxApplicants?: Prisma.IntFilter<"Listing"> | number
  currentApplicants?: Prisma.IntFilter<"Listing"> | number
  status?: Prisma.EnumListingStatusFilter<"Listing"> | $Enums.ListingStatus
  autoClosedAt?: Prisma.DateTimeNullableFilter<"Listing"> | Date | string | null
  closedReason?: Prisma.StringNullableFilter<"Listing"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Listing"> | Date | string
  targetBranch?: Prisma.StringNullableFilter<"Listing"> | string | null
  targetGradYear?: Prisma.IntNullableFilter<"Listing"> | number | null
}

export type ListingCreateWithoutRequiredSkillsInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  company: Prisma.CompanyCreateNestedOneWithoutListingsInput
  preferredSkills?: Prisma.ListingPreferredSkillCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutListingInput
}

export type ListingUncheckedCreateWithoutRequiredSkillsInput = {
  id?: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutListingInput
}

export type ListingCreateOrConnectWithoutRequiredSkillsInput = {
  where: Prisma.ListingWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCreateWithoutRequiredSkillsInput, Prisma.ListingUncheckedCreateWithoutRequiredSkillsInput>
}

export type ListingUpsertWithoutRequiredSkillsInput = {
  update: Prisma.XOR<Prisma.ListingUpdateWithoutRequiredSkillsInput, Prisma.ListingUncheckedUpdateWithoutRequiredSkillsInput>
  create: Prisma.XOR<Prisma.ListingCreateWithoutRequiredSkillsInput, Prisma.ListingUncheckedCreateWithoutRequiredSkillsInput>
  where?: Prisma.ListingWhereInput
}

export type ListingUpdateToOneWithWhereWithoutRequiredSkillsInput = {
  where?: Prisma.ListingWhereInput
  data: Prisma.XOR<Prisma.ListingUpdateWithoutRequiredSkillsInput, Prisma.ListingUncheckedUpdateWithoutRequiredSkillsInput>
}

export type ListingUpdateWithoutRequiredSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  company?: Prisma.CompanyUpdateOneRequiredWithoutListingsNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateWithoutRequiredSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutListingNestedInput
}

export type ListingCreateWithoutPreferredSkillsInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  company: Prisma.CompanyCreateNestedOneWithoutListingsInput
  requiredSkills?: Prisma.ListingRequiredSkillCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutListingInput
}

export type ListingUncheckedCreateWithoutPreferredSkillsInput = {
  id?: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedCreateNestedManyWithoutListingInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutListingInput
}

export type ListingCreateOrConnectWithoutPreferredSkillsInput = {
  where: Prisma.ListingWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCreateWithoutPreferredSkillsInput, Prisma.ListingUncheckedCreateWithoutPreferredSkillsInput>
}

export type ListingUpsertWithoutPreferredSkillsInput = {
  update: Prisma.XOR<Prisma.ListingUpdateWithoutPreferredSkillsInput, Prisma.ListingUncheckedUpdateWithoutPreferredSkillsInput>
  create: Prisma.XOR<Prisma.ListingCreateWithoutPreferredSkillsInput, Prisma.ListingUncheckedCreateWithoutPreferredSkillsInput>
  where?: Prisma.ListingWhereInput
}

export type ListingUpdateToOneWithWhereWithoutPreferredSkillsInput = {
  where?: Prisma.ListingWhereInput
  data: Prisma.XOR<Prisma.ListingUpdateWithoutPreferredSkillsInput, Prisma.ListingUncheckedUpdateWithoutPreferredSkillsInput>
}

export type ListingUpdateWithoutPreferredSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  company?: Prisma.CompanyUpdateOneRequiredWithoutListingsNestedInput
  requiredSkills?: Prisma.ListingRequiredSkillUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateWithoutPreferredSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutListingNestedInput
}

export type ListingCreateWithoutApplicationsInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  company: Prisma.CompanyCreateNestedOneWithoutListingsInput
  requiredSkills?: Prisma.ListingRequiredSkillCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillCreateNestedManyWithoutListingInput
}

export type ListingUncheckedCreateWithoutApplicationsInput = {
  id?: string
  companyId: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedCreateNestedManyWithoutListingInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedCreateNestedManyWithoutListingInput
}

export type ListingCreateOrConnectWithoutApplicationsInput = {
  where: Prisma.ListingWhereUniqueInput
  create: Prisma.XOR<Prisma.ListingCreateWithoutApplicationsInput, Prisma.ListingUncheckedCreateWithoutApplicationsInput>
}

export type ListingUpsertWithoutApplicationsInput = {
  update: Prisma.XOR<Prisma.ListingUpdateWithoutApplicationsInput, Prisma.ListingUncheckedUpdateWithoutApplicationsInput>
  create: Prisma.XOR<Prisma.ListingCreateWithoutApplicationsInput, Prisma.ListingUncheckedCreateWithoutApplicationsInput>
  where?: Prisma.ListingWhereInput
}

export type ListingUpdateToOneWithWhereWithoutApplicationsInput = {
  where?: Prisma.ListingWhereInput
  data: Prisma.XOR<Prisma.ListingUpdateWithoutApplicationsInput, Prisma.ListingUncheckedUpdateWithoutApplicationsInput>
}

export type ListingUpdateWithoutApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  company?: Prisma.CompanyUpdateOneRequiredWithoutListingsNestedInput
  requiredSkills?: Prisma.ListingRequiredSkillUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateWithoutApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutListingNestedInput
}

export type ListingCreateManyCompanyInput = {
  id?: string
  title: string
  description: string
  stipend: number
  location: $Enums.Location
  deadline: Date | string
  maxApplicants: number
  currentApplicants?: number
  status?: $Enums.ListingStatus
  autoClosedAt?: Date | string | null
  closedReason?: string | null
  createdAt?: Date | string
  targetBranch?: string | null
  targetGradYear?: number | null
}

export type ListingUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiredSkills?: Prisma.ListingRequiredSkillUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiredSkills?: Prisma.ListingRequiredSkillUncheckedUpdateManyWithoutListingNestedInput
  preferredSkills?: Prisma.ListingPreferredSkillUncheckedUpdateManyWithoutListingNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutListingNestedInput
}

export type ListingUncheckedUpdateManyWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  stipend?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  currentApplicants?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumListingStatusFieldUpdateOperationsInput | $Enums.ListingStatus
  autoClosedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  targetBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetGradYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type ListingCountOutputType
 */

export type ListingCountOutputType = {
  requiredSkills: number
  preferredSkills: number
  applications: number
}

export type ListingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requiredSkills?: boolean | ListingCountOutputTypeCountRequiredSkillsArgs
  preferredSkills?: boolean | ListingCountOutputTypeCountPreferredSkillsArgs
  applications?: boolean | ListingCountOutputTypeCountApplicationsArgs
}

/**
 * ListingCountOutputType without action
 */
export type ListingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingCountOutputType
   */
  select?: Prisma.ListingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ListingCountOutputType without action
 */
export type ListingCountOutputTypeCountRequiredSkillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingRequiredSkillWhereInput
}

/**
 * ListingCountOutputType without action
 */
export type ListingCountOutputTypeCountPreferredSkillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingPreferredSkillWhereInput
}

/**
 * ListingCountOutputType without action
 */
export type ListingCountOutputTypeCountApplicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationWhereInput
}


export type ListingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  title?: boolean
  description?: boolean
  stipend?: boolean
  location?: boolean
  deadline?: boolean
  maxApplicants?: boolean
  currentApplicants?: boolean
  status?: boolean
  autoClosedAt?: boolean
  closedReason?: boolean
  createdAt?: boolean
  targetBranch?: boolean
  targetGradYear?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  requiredSkills?: boolean | Prisma.Listing$requiredSkillsArgs<ExtArgs>
  preferredSkills?: boolean | Prisma.Listing$preferredSkillsArgs<ExtArgs>
  applications?: boolean | Prisma.Listing$applicationsArgs<ExtArgs>
  _count?: boolean | Prisma.ListingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listing"]>

export type ListingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  title?: boolean
  description?: boolean
  stipend?: boolean
  location?: boolean
  deadline?: boolean
  maxApplicants?: boolean
  currentApplicants?: boolean
  status?: boolean
  autoClosedAt?: boolean
  closedReason?: boolean
  createdAt?: boolean
  targetBranch?: boolean
  targetGradYear?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listing"]>

export type ListingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  title?: boolean
  description?: boolean
  stipend?: boolean
  location?: boolean
  deadline?: boolean
  maxApplicants?: boolean
  currentApplicants?: boolean
  status?: boolean
  autoClosedAt?: boolean
  closedReason?: boolean
  createdAt?: boolean
  targetBranch?: boolean
  targetGradYear?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listing"]>

export type ListingSelectScalar = {
  id?: boolean
  companyId?: boolean
  title?: boolean
  description?: boolean
  stipend?: boolean
  location?: boolean
  deadline?: boolean
  maxApplicants?: boolean
  currentApplicants?: boolean
  status?: boolean
  autoClosedAt?: boolean
  closedReason?: boolean
  createdAt?: boolean
  targetBranch?: boolean
  targetGradYear?: boolean
}

export type ListingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "companyId" | "title" | "description" | "stipend" | "location" | "deadline" | "maxApplicants" | "currentApplicants" | "status" | "autoClosedAt" | "closedReason" | "createdAt" | "targetBranch" | "targetGradYear", ExtArgs["result"]["listing"]>
export type ListingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  requiredSkills?: boolean | Prisma.Listing$requiredSkillsArgs<ExtArgs>
  preferredSkills?: boolean | Prisma.Listing$preferredSkillsArgs<ExtArgs>
  applications?: boolean | Prisma.Listing$applicationsArgs<ExtArgs>
  _count?: boolean | Prisma.ListingCountOutputTypeDefaultArgs<ExtArgs>
}
export type ListingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type ListingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}

export type $ListingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Listing"
  objects: {
    company: Prisma.$CompanyPayload<ExtArgs>
    requiredSkills: Prisma.$ListingRequiredSkillPayload<ExtArgs>[]
    preferredSkills: Prisma.$ListingPreferredSkillPayload<ExtArgs>[]
    applications: Prisma.$ApplicationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    companyId: string
    title: string
    description: string
    stipend: number
    location: $Enums.Location
    deadline: Date
    maxApplicants: number
    currentApplicants: number
    status: $Enums.ListingStatus
    autoClosedAt: Date | null
    closedReason: string | null
    createdAt: Date
    targetBranch: string | null
    targetGradYear: number | null
  }, ExtArgs["result"]["listing"]>
  composites: {}
}

export type ListingGetPayload<S extends boolean | null | undefined | ListingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingPayload, S>

export type ListingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingCountAggregateInputType | true
  }

export interface ListingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Listing'], meta: { name: 'Listing' } }
  /**
   * Find zero or one Listing that matches the filter.
   * @param {ListingFindUniqueArgs} args - Arguments to find a Listing
   * @example
   * // Get one Listing
   * const listing = await prisma.listing.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Listing that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingFindUniqueOrThrowArgs} args - Arguments to find a Listing
   * @example
   * // Get one Listing
   * const listing = await prisma.listing.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Listing that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFindFirstArgs} args - Arguments to find a Listing
   * @example
   * // Get one Listing
   * const listing = await prisma.listing.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Listing that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFindFirstOrThrowArgs} args - Arguments to find a Listing
   * @example
   * // Get one Listing
   * const listing = await prisma.listing.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Listings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Listings
   * const listings = await prisma.listing.findMany()
   * 
   * // Get first 10 Listings
   * const listings = await prisma.listing.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listingWithIdOnly = await prisma.listing.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ListingFindManyArgs>(args?: Prisma.SelectSubset<T, ListingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Listing.
   * @param {ListingCreateArgs} args - Arguments to create a Listing.
   * @example
   * // Create one Listing
   * const Listing = await prisma.listing.create({
   *   data: {
   *     // ... data to create a Listing
   *   }
   * })
   * 
   */
  create<T extends ListingCreateArgs>(args: Prisma.SelectSubset<T, ListingCreateArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Listings.
   * @param {ListingCreateManyArgs} args - Arguments to create many Listings.
   * @example
   * // Create many Listings
   * const listing = await prisma.listing.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Listings and returns the data saved in the database.
   * @param {ListingCreateManyAndReturnArgs} args - Arguments to create many Listings.
   * @example
   * // Create many Listings
   * const listing = await prisma.listing.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Listings and only return the `id`
   * const listingWithIdOnly = await prisma.listing.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Listing.
   * @param {ListingDeleteArgs} args - Arguments to delete one Listing.
   * @example
   * // Delete one Listing
   * const Listing = await prisma.listing.delete({
   *   where: {
   *     // ... filter to delete one Listing
   *   }
   * })
   * 
   */
  delete<T extends ListingDeleteArgs>(args: Prisma.SelectSubset<T, ListingDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Listing.
   * @param {ListingUpdateArgs} args - Arguments to update one Listing.
   * @example
   * // Update one Listing
   * const listing = await prisma.listing.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingUpdateArgs>(args: Prisma.SelectSubset<T, ListingUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Listings.
   * @param {ListingDeleteManyArgs} args - Arguments to filter Listings to delete.
   * @example
   * // Delete a few Listings
   * const { count } = await prisma.listing.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Listings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Listings
   * const listing = await prisma.listing.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Listings and returns the data updated in the database.
   * @param {ListingUpdateManyAndReturnArgs} args - Arguments to update many Listings.
   * @example
   * // Update many Listings
   * const listing = await prisma.listing.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Listings and only return the `id`
   * const listingWithIdOnly = await prisma.listing.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Listing.
   * @param {ListingUpsertArgs} args - Arguments to update or create a Listing.
   * @example
   * // Update or create a Listing
   * const listing = await prisma.listing.upsert({
   *   create: {
   *     // ... data to create a Listing
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Listing we want to update
   *   }
   * })
   */
  upsert<T extends ListingUpsertArgs>(args: Prisma.SelectSubset<T, ListingUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingClient<runtime.Types.Result.GetResult<Prisma.$ListingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Listings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingCountArgs} args - Arguments to filter Listings to count.
   * @example
   * // Count the number of Listings
   * const count = await prisma.listing.count({
   *   where: {
   *     // ... the filter for the Listings we want to count
   *   }
   * })
  **/
  count<T extends ListingCountArgs>(
    args?: Prisma.Subset<T, ListingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Listing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingAggregateArgs>(args: Prisma.Subset<T, ListingAggregateArgs>): Prisma.PrismaPromise<GetListingAggregateType<T>>

  /**
   * Group by Listing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingGroupByArgs['orderBy'] }
      : { orderBy?: ListingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Listing model
 */
readonly fields: ListingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Listing.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  company<T extends Prisma.CompanyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompanyDefaultArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  requiredSkills<T extends Prisma.Listing$requiredSkillsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Listing$requiredSkillsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingRequiredSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  preferredSkills<T extends Prisma.Listing$preferredSkillsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Listing$preferredSkillsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingPreferredSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  applications<T extends Prisma.Listing$applicationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Listing$applicationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Listing model
 */
export interface ListingFieldRefs {
  readonly id: Prisma.FieldRef<"Listing", 'String'>
  readonly companyId: Prisma.FieldRef<"Listing", 'String'>
  readonly title: Prisma.FieldRef<"Listing", 'String'>
  readonly description: Prisma.FieldRef<"Listing", 'String'>
  readonly stipend: Prisma.FieldRef<"Listing", 'Float'>
  readonly location: Prisma.FieldRef<"Listing", 'Location'>
  readonly deadline: Prisma.FieldRef<"Listing", 'DateTime'>
  readonly maxApplicants: Prisma.FieldRef<"Listing", 'Int'>
  readonly currentApplicants: Prisma.FieldRef<"Listing", 'Int'>
  readonly status: Prisma.FieldRef<"Listing", 'ListingStatus'>
  readonly autoClosedAt: Prisma.FieldRef<"Listing", 'DateTime'>
  readonly closedReason: Prisma.FieldRef<"Listing", 'String'>
  readonly createdAt: Prisma.FieldRef<"Listing", 'DateTime'>
  readonly targetBranch: Prisma.FieldRef<"Listing", 'String'>
  readonly targetGradYear: Prisma.FieldRef<"Listing", 'Int'>
}
    

// Custom InputTypes
/**
 * Listing findUnique
 */
export type ListingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter, which Listing to fetch.
   */
  where: Prisma.ListingWhereUniqueInput
}

/**
 * Listing findUniqueOrThrow
 */
export type ListingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter, which Listing to fetch.
   */
  where: Prisma.ListingWhereUniqueInput
}

/**
 * Listing findFirst
 */
export type ListingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter, which Listing to fetch.
   */
  where?: Prisma.ListingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Listings to fetch.
   */
  orderBy?: Prisma.ListingOrderByWithRelationInput | Prisma.ListingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Listings.
   */
  cursor?: Prisma.ListingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Listings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Listings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Listings.
   */
  distinct?: Prisma.ListingScalarFieldEnum | Prisma.ListingScalarFieldEnum[]
}

/**
 * Listing findFirstOrThrow
 */
export type ListingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter, which Listing to fetch.
   */
  where?: Prisma.ListingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Listings to fetch.
   */
  orderBy?: Prisma.ListingOrderByWithRelationInput | Prisma.ListingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Listings.
   */
  cursor?: Prisma.ListingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Listings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Listings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Listings.
   */
  distinct?: Prisma.ListingScalarFieldEnum | Prisma.ListingScalarFieldEnum[]
}

/**
 * Listing findMany
 */
export type ListingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter, which Listings to fetch.
   */
  where?: Prisma.ListingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Listings to fetch.
   */
  orderBy?: Prisma.ListingOrderByWithRelationInput | Prisma.ListingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Listings.
   */
  cursor?: Prisma.ListingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Listings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Listings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Listings.
   */
  distinct?: Prisma.ListingScalarFieldEnum | Prisma.ListingScalarFieldEnum[]
}

/**
 * Listing create
 */
export type ListingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * The data needed to create a Listing.
   */
  data: Prisma.XOR<Prisma.ListingCreateInput, Prisma.ListingUncheckedCreateInput>
}

/**
 * Listing createMany
 */
export type ListingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Listings.
   */
  data: Prisma.ListingCreateManyInput | Prisma.ListingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Listing createManyAndReturn
 */
export type ListingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * The data used to create many Listings.
   */
  data: Prisma.ListingCreateManyInput | Prisma.ListingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Listing update
 */
export type ListingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * The data needed to update a Listing.
   */
  data: Prisma.XOR<Prisma.ListingUpdateInput, Prisma.ListingUncheckedUpdateInput>
  /**
   * Choose, which Listing to update.
   */
  where: Prisma.ListingWhereUniqueInput
}

/**
 * Listing updateMany
 */
export type ListingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Listings.
   */
  data: Prisma.XOR<Prisma.ListingUpdateManyMutationInput, Prisma.ListingUncheckedUpdateManyInput>
  /**
   * Filter which Listings to update
   */
  where?: Prisma.ListingWhereInput
  /**
   * Limit how many Listings to update.
   */
  limit?: number
}

/**
 * Listing updateManyAndReturn
 */
export type ListingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * The data used to update Listings.
   */
  data: Prisma.XOR<Prisma.ListingUpdateManyMutationInput, Prisma.ListingUncheckedUpdateManyInput>
  /**
   * Filter which Listings to update
   */
  where?: Prisma.ListingWhereInput
  /**
   * Limit how many Listings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Listing upsert
 */
export type ListingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * The filter to search for the Listing to update in case it exists.
   */
  where: Prisma.ListingWhereUniqueInput
  /**
   * In case the Listing found by the `where` argument doesn't exist, create a new Listing with this data.
   */
  create: Prisma.XOR<Prisma.ListingCreateInput, Prisma.ListingUncheckedCreateInput>
  /**
   * In case the Listing was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingUpdateInput, Prisma.ListingUncheckedUpdateInput>
}

/**
 * Listing delete
 */
export type ListingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
  /**
   * Filter which Listing to delete.
   */
  where: Prisma.ListingWhereUniqueInput
}

/**
 * Listing deleteMany
 */
export type ListingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Listings to delete
   */
  where?: Prisma.ListingWhereInput
  /**
   * Limit how many Listings to delete.
   */
  limit?: number
}

/**
 * Listing.requiredSkills
 */
export type Listing$requiredSkillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingRequiredSkill
   */
  select?: Prisma.ListingRequiredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingRequiredSkill
   */
  omit?: Prisma.ListingRequiredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingRequiredSkillInclude<ExtArgs> | null
  where?: Prisma.ListingRequiredSkillWhereInput
  orderBy?: Prisma.ListingRequiredSkillOrderByWithRelationInput | Prisma.ListingRequiredSkillOrderByWithRelationInput[]
  cursor?: Prisma.ListingRequiredSkillWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ListingRequiredSkillScalarFieldEnum | Prisma.ListingRequiredSkillScalarFieldEnum[]
}

/**
 * Listing.preferredSkills
 */
export type Listing$preferredSkillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingPreferredSkill
   */
  select?: Prisma.ListingPreferredSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingPreferredSkill
   */
  omit?: Prisma.ListingPreferredSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingPreferredSkillInclude<ExtArgs> | null
  where?: Prisma.ListingPreferredSkillWhereInput
  orderBy?: Prisma.ListingPreferredSkillOrderByWithRelationInput | Prisma.ListingPreferredSkillOrderByWithRelationInput[]
  cursor?: Prisma.ListingPreferredSkillWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ListingPreferredSkillScalarFieldEnum | Prisma.ListingPreferredSkillScalarFieldEnum[]
}

/**
 * Listing.applications
 */
export type Listing$applicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationInclude<ExtArgs> | null
  where?: Prisma.ApplicationWhereInput
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  cursor?: Prisma.ApplicationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApplicationScalarFieldEnum | Prisma.ApplicationScalarFieldEnum[]
}

/**
 * Listing without action
 */
export type ListingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Listing
   */
  select?: Prisma.ListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Listing
   */
  omit?: Prisma.ListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListingInclude<ExtArgs> | null
}
