
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model Skill
 * 
 */
export type Skill = Prisma.SkillModel
/**
 * Model StudentSkill
 * 
 */
export type StudentSkill = Prisma.StudentSkillModel
/**
 * Model Company
 * 
 */
export type Company = Prisma.CompanyModel
/**
 * Model Listing
 * 
 */
export type Listing = Prisma.ListingModel
/**
 * Model ListingRequiredSkill
 * 
 */
export type ListingRequiredSkill = Prisma.ListingRequiredSkillModel
/**
 * Model ListingPreferredSkill
 * 
 */
export type ListingPreferredSkill = Prisma.ListingPreferredSkillModel
/**
 * Model Application
 * 
 */
export type Application = Prisma.ApplicationModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
