
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Location = {
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
  ONSITE: 'ONSITE'
} as const

export type Location = (typeof Location)[keyof typeof Location]


export const ListingStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED'
} as const

export type ListingStatus = (typeof ListingStatus)[keyof typeof ListingStatus]


export const ApplicationStatus = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  REJECTED: 'REJECTED',
  OFFER_EXTENDED: 'OFFER_EXTENDED'
} as const

export type ApplicationStatus = (typeof ApplicationStatus)[keyof typeof ApplicationStatus]


export const RecipientType = {
  STUDENT: 'STUDENT',
  COMPANY: 'COMPANY'
} as const

export type RecipientType = (typeof RecipientType)[keyof typeof RecipientType]
