
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Student'
export type * from './models/Skill'
export type * from './models/StudentSkill'
export type * from './models/Company'
export type * from './models/Listing'
export type * from './models/ListingRequiredSkill'
export type * from './models/ListingPreferredSkill'
export type * from './models/Application'
export type * from './models/Notification'
export type * from './commonInputTypes'